print("Hello world!")
name = input("Enter your name: ")
print("hello, " + name + "!")  
age = input ("Enter your age: ")
age = int(age)
print ("You will be " + str(age) + "next year")
print (f"I am {age} next year")